## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [8]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN','NAME'])

KeyError: "['EIN', 'NAME'] not found in axis"

In [9]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [17]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [18]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_type_count = application_df['APPLICATION_TYPE'].value_counts()
app_type_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [22]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
app_types_replaced = list(app_type_count[app_type_count < 500].index)

# Replace in dataframe
for app in app_types_replaced:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [25]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_type_count = application_df['CLASSIFICATION'].value_counts()
class_type_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [26]:
# You may find it helpful to look at CLASSIFICATION value counts >1
counts = application_df['CLASSIFICATION'].value_counts()
class_greater_than_one = counts[counts > 1]

class_greater_than_one

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [27]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_types_replaced = list(class_type_count[class_type_count < 1800].index)
# Replace in dataframe
for cls in class_types_replaced:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [28]:
# Convert categorical data to numeric with `pd.get_dummies`
app_dummies_df = pd.get_dummies(application_df, dtype = int)
app_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [29]:
# Split our preprocessed data into our features and target arrays
y = app_dummies_df['IS_SUCCESSFUL']
X = app_dummies_df.drop (columns = 'IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [30]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [34]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=43))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 993 (3.88 KB)

 Trainable params: 993 (3.88 KB)

 Non-trainable params: 0 (0.00 B)

In [35]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [36]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 384us/step - accuracy: 0.6807 - loss: 0.6161
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7234 - loss: 0.5653
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7284 - loss: 0.5570
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 253us/step - accuracy: 0.7314 - loss: 0.5527
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 250us/step - accuracy: 0.7344 - loss: 0.5491
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7267 - loss: 0.5547
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 252us/step - accuracy: 0.7390 - loss: 0.5426
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 255us/step - accuracy: 0.7369 - loss: 0.5439
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - accuracy: 0.7289 - loss: 0.5545
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 253us/step - accuracy: 0.7317 - loss: 0.5489
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 251us/step - accuracy: 0.7322 - loss: 0.5492
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7357 - loss: 0.5451
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7334 - loss: 0.5461
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7349 - loss: 0.5447
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7292 - loss: 0.5523
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7323 - loss: 0.5472
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 295us/step - accuracy: 0.7326 - loss: 0.5486
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7303 - loss: 0.5488
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.7316 - loss: 0.5485
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 260us/step - accuracy: 0.7354 - loss: 0.5463
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 255us/step - accuracy: 0.7357 - loss: 0.5443
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7418 - loss: 0.5377
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7352 - loss: 0.5443
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7317 - loss: 0.5489
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - accuracy: 0.7352 - loss: 0.5422
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.7342 - loss: 0.5446
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7386 - loss: 0.5421
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7346 - loss: 0.5438
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 249us/step - accuracy: 0.7306 - loss: 0.5475
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 260us/step - accuracy: 0.7392 - loss: 0.5437
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7371 - loss: 0.5430
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 260us/step - accuracy: 0.7321 - loss: 0.5496
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 255us/step - accuracy: 0.7353 - loss: 0.5443
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7382 - loss: 0.5417
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7374 - loss: 0.5430
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7286 - loss: 0.5523
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 263us/step - accuracy: 0.7388 - loss: 0.5402
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - accuracy: 0.7405 - loss: 0.5401
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7387 - loss: 0.5393
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.7364 - loss: 0.5435
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7361 - loss: 0.5423
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7390 - loss: 0.5415
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7359 - loss: 0.5453
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7367 - loss: 0.5437
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 262us/step - accuracy: 0.7377 - loss: 0.5430
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 260us/step - accuracy: 0.7333 - loss: 0.5430
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 255us/step - accuracy: 0.7332 - loss: 0.5442
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 326us/step - accuracy: 0.7386 - loss: 0.5419
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.7379 - loss: 0.5389
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7351 - loss: 0.5428
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7348 - loss: 0.5427
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7377 - loss: 0.5430
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7363 - loss: 0.5417
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7394 - loss: 0.5367
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7384 - loss: 0.5387
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 253us/step - accuracy: 0.7384 - loss: 0.5385
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7364 - loss: 0.5398
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 253us/step - accuracy: 0.7357 - loss: 0.5436
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7402 - loss: 0.5356
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7391 - loss: 0.5389
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7356 - loss: 0.5409
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.7397 - loss: 0.5401
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 267us/step - accuracy: 0.7375 - loss: 0.5402
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 263us/step - accuracy: 0.7426 - loss: 0.5374
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 269us/step - accuracy: 0.7396 - loss: 0.5393
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 260us/step - accuracy: 0.7343 - loss: 0.5422
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7368 - loss: 0.5396
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7366 - loss: 0.5427
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 253us/step - accuracy: 0.7379 - loss: 0.5394
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.7407 - loss: 0.5392
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7360 - loss: 0.5407
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7321 - loss: 0.5453
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.7361 - loss: 0.5409
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 252us/step - accuracy: 0.7359 - loss: 0.5422
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7379 - loss: 0.5354
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 255us/step - accuracy: 0.7366 - loss: 0.5422
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7343 - loss: 0.5456
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7352 - loss: 0.5412
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 253us/step - accuracy: 0.7386 - loss: 0.5389
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7384 - loss: 0.5405
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7331 - loss: 0.5431
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7356 - loss: 0.5412
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7359 - loss: 0.5424
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7362 - loss: 0.5380
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 307us/step - accuracy: 0.7421 - loss: 0.5346
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7412 - loss: 0.5366
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 264us/step - accuracy: 0.7373 - loss: 0.5399
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7394 - loss: 0.5399
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 262us/step - accuracy: 0.7426 - loss: 0.5328
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.7342 - loss: 0.5400
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 260us/step - accuracy: 0.7384 - loss: 0.5394
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.7375 - loss: 0.5388
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7375 - loss: 0.5378
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 297us/step - accuracy: 0.7400 - loss: 0.5391
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 258us/step - accuracy: 0.7364 - loss: 0.5382
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 264us/step - accuracy: 0.7392 - loss: 0.5380
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7389 - loss: 0.5381
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.7390 - loss: 0.5349
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.7417 - loss: 0.5364
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 255us/step - accuracy: 0.7419 - loss: 0.5337

In [37]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 403us/step - accuracy: 0.7266 - loss: 0.5519
Loss: 0.5518715381622314, Accuracy: 0.7266472578048706

In [38]:
# Export our model to HDF5 file
nn_model.save('module21.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.